### PR TITLE
add CMake testing results for t{12,13,14,18,19}

### PR DESCRIPTION
**Pull request by alexsavulescu**
Using `oversub` branch to test integration of this repository into `nrn` 
https://github.com/neuronsimulator/nrn/pull/1434 

All these updates are needed in order to have the CI pipelines working. Small note, there are two pipelines that pass without these updates.

### CODE REVIEW

**Comment by nrnhines** [comment]
I'm occasionally getting an error on my linux desktop with t12.hoc ranging from segfaults to
```
~/neuron/add-nrntest/build$ ctest -VV -R external_nrntest
20: t12.hoc stdout: nrniv: ../src/nrncvode/cvodeobj.cpp:774:  bool Cvode::at_time(double, NrnThread*): Assertion `te > tstop_ || te <= t0_' failed.
20: t12.hoc failed
```

When I run
```
~/neuron/add-nrntest/external/tests/nrntest/fast$ valgrind --tool=helgrind nrniv -nogui -nopython t12.hoc
```
it generates  two types of race. There are a lot of:
```
==57673== Possible data race during write of size 8 at 0x92189A0 by thread #3
==57673== Locks held: none
==57673==    at 0x5148FA3: HTList::Remove() (htlist.cpp:72)
==57673==    by 0x51C5995: _nrn_watch_activate (netcvode.cpp:2449)
==57673==    by 0x9321B8E: _net_receive__t12 (t12.c:313)
==57673==    by 0x51D2F25: WatchCondition::deliver(double, NetCvode*, NrnThread*) (netcvode.cpp:5376)
...
==57673== This conflicts with a previous read of size 8 by thread #2
==57673== Locks held: none
==57673==    at 0x51491D8: HTList::First() (htlist.h:64)
==57673==    by 0x51D4D6C: NetCvode::check_thresh(NrnThread*) (netcvode.cpp:5887)
==57673==    by 0x51BADE5: deliver_net_events(NrnThread*) (cvodestb.cpp:43)
```
And a few of:
```
==57673== Possible data race during read of size 8 at 0x910C130 by thread #3
==57673== Locks held: none
==57673==    at 0x51B7D96: Cvode::at_time(double, NrnThread*) (cvodeobj.cpp:750)
==57673==    by 0x51BB10F: at_time (cvodestb.cpp:133)
==57673==    by 0x5382A95: _nrn_current__IClamp (stim.c:266)
...
==57673== This conflicts with a previous write of size 8 by thread #1
==57673== Locks held: none
==57673==    at 0x51B7DAE: Cvode::at_time(double, NrnThread*) (cvodeobj.cpp:752)
==57673==    by 0x51BB10F: at_time (cvodestb.cpp:133)
==57673==    by 0x5382A95: _nrn_current__IClamp (stim.c:266)
```
The latter is particularly puzzling since the code is surrounded by MUTLOCK...MUTUNLOCK macros. ie.
```
                MUTLOCK
                if (t0_ < te && te < next_at_time_) {
                        next_at_time_ = te;
                }
                MUTUNLOCK
```
I'm first going to check to see if these race notices precede the neuronsimulator/nrn#1192 changes.

**Comment by alexsavulescu** [comment]
Didn't look into that yet, was trying to reproduce the deadlock. But maybe fixing those will inherently take care of the deadlock.

**Comment by alexsavulescu** [comment]
> it generates two types of race.

Can corroborate with `ThreadSanitizer` from gcc: 
```
(venv) savulesc@bbd-cjngk03:~/Workspace/nrn/bldnrntest$ cat b | grep ThreadSanitizer | grep SUMMARY
94: SUMMARY: ThreadSanitizer: data race /home/savulesc/Workspace/nrn/src/ivoc/htlist.cpp:72 in HTList::Remove()
94: SUMMARY: ThreadSanitizer: data race /home/savulesc/Workspace/nrn/src/ivoc/htlist.cpp:74 in HTList::Remove()
94: SUMMARY: ThreadSanitizer: data race /home/savulesc/Workspace/nrn/src/ivoc/htlist.cpp:72 in HTList::Remove()
94: SUMMARY: ThreadSanitizer: data race /home/savulesc/Workspace/nrn/src/ivoc/htlist.cpp:74 in HTList::Remove()
94: SUMMARY: ThreadSanitizer: data race /home/savulesc/Workspace/nrn/src/ivoc/htlist.cpp:74 in HTList::Remove()
94: SUMMARY: ThreadSanitizer: data race /home/savulesc/Workspace/nrn/src/ivoc/htlist.cpp:72 in HTList::Remove()
94: SUMMARY: ThreadSanitizer: data race /home/savulesc/Workspace/nrn/src/ivoc/htlist.cpp:74 in HTList::Remove()
94: SUMMARY: ThreadSanitizer: data race /home/savulesc/Workspace/nrn/src/ivoc/htlist.cpp:74 in HTList::Remove()
94: SUMMARY: ThreadSanitizer: data race /home/savulesc/Workspace/nrn/src/nrncvode/cvodeobj.cpp:751 in Cvode::at_time(double, NrnThread*)
94: SUMMARY: ThreadSanitizer: data race /home/savulesc/Workspace/nrn/src/nrncvode/cvodeobj.cpp:751 in Cvode::at_time(double, NrnThread*)
```

How to enable thread sanitizer (I have gcc 9.3.0):
```
cmake -G Ninja .......  -DNRN_ENABLE_TESTS=ON -DCMAKE_C_FLAGS="-O0 -fno-inline -g -fsanitize=thread" -DCMAKE_CXX_FLAGS="-O0 -fno-inline -g -fsanitize=thread" ..
```


> The latter is particularly puzzling since the code is surrounded by MUTLOCK...MUTUNLOCK macros. ie.

Actually for CVode we didn't have an initialized mutex. Went for some logging:
```diff
 git diff ../src/ivoc/nrnmutdec.h
diff --git a/src/ivoc/nrnmutdec.h b/src/ivoc/nrnmutdec.h
index ce28825a8..9295c4a31 100644
--- a/src/ivoc/nrnmutdec.h
+++ b/src/ivoc/nrnmutdec.h
@@ -6,6 +6,8 @@
 
 #include <pthread.h>
 
+#define llll(t) printf("%s: %s(%s:%d) \n", t, __func__,__FILE__, __LINE__);
+
 #ifdef MINGW
 #undef DELETE
 #undef near
@@ -14,23 +16,23 @@
 #define MUTDEC pthread_mutex_t* mut_;
 #define MUTCONSTRUCTED (mut_ != (pthread_mutex_t*)0)
 #if defined(__cplusplus)
-#define MUTCONSTRUCT(mkmut) {if (mkmut) {mut_ = new pthread_mutex_t; pthread_mutex_init(mut_, 0);}else{mut_ = 0;}}
-#define MUTDESTRUCT {if (mut_){pthread_mutex_destroy(mut_); delete mut_; mut_ = (pthread_mutex_t*)0;}}
+#define MUTCONSTRUCT(mkmut) {llll("init-cpp-enter") if (mkmut) {llll("init-cpp") mut_ = new pthread_mutex_t; pthread_mutex_init(mut_, 0);}else{mut_ = 0;}}
+#define MUTDESTRUCT {llll("des-cpp-enter") if (mut_){llll("des-cpp") pthread_mutex_destroy(mut_); delete mut_; mut_ = (pthread_mutex_t*)0;}}
 #else
-#define MUTCONSTRUCT(mkmut) {if (mkmut) {mut_ = (pthread_mutex_t*)malloc(sizeof(pthread_mutex_t)); pthread_mutex_init(mut_, 0);}else{mut_ = 0;}}
-#define MUTDESTRUCT {if (mut_){pthread_mutex_destroy(mut_); free(mut_); mut_ = NULL;}}
+#define MUTCONSTRUCT(mkmut) {llll("init enter") if (mkmut) {llll("init") mut_ = (pthread_mutex_t*)malloc(sizeof(pthread_mutex_t)); pthread_mutex_init(mut_, 0);}else{mut_ = 0;}}
+#define MUTDESTRUCT {llll("des enter") if (mut_){llll("init") pthread_mutex_destroy(mut_); free(mut_); mut_ = NULL;}}
 #endif
-#define MUTLOCK {if (mut_) {pthread_mutex_lock(mut_);}}
-#define MUTUNLOCK {if (mut_) {pthread_mutex_unlock(mut_);}}
+#define MUTLOCK {llll("lock-enter") if (mut_) {llll("lock") pthread_mutex_lock(mut_);}}
+#define MUTUNLOCK {llll("unlock-enter") if (mut_) {llll("unlock") pthread_mutex_unlock(mut_);}}
 /*#define MUTLOCK {if (mut_) {printf("lock %lx\n", mut_); pthread_mutex_lock(mut_);}}*/
 /*#define MUTUNLOCK {if (mut_) {printf("unlock %lx\n", mut_); pthread_mutex_unlock(mut_);}}*/
 #else
 #define MUTDEC /**/
 #define MUTCONSTRUCTED (0)
-#define MUTCONSTRUCT(mkmut) /**/
+#define MUTCONSTRUCT(mkmut) llll("boom")/**/
 #define MUTDESTRUCT /**/
-#define MUTLOCK /**/
-#define MUTUNLOCK /**/
+#define MUTLOCK llll("booml")/**/
+#define MUTUNLOCK llll("boomu")/**/
 #endif
 
 #endif

```

So I've added a `MUTCONSTRUCT` in the Cvode construction phase and ThreadSanitizer doesn't report that data race anymore:
```
(venv) savulesc@bbd-cjngk03:~/Workspace/nrn/bldnrntest$ cat a | grep ThreadSanitizer | grep SUMMARY
94: SUMMARY: ThreadSanitizer: data race /home/savulesc/Workspace/nrn/src/ivoc/htlist.cpp:72 in HTList::Remove()
94: SUMMARY: ThreadSanitizer: data race /home/savulesc/Workspace/nrn/src/ivoc/htlist.cpp:74 in HTList::Remove()
94: SUMMARY: ThreadSanitizer: data race /home/savulesc/Workspace/nrn/src/ivoc/htlist.cpp:74 in HTList::Remove()
94: SUMMARY: ThreadSanitizer: data race /home/savulesc/Workspace/nrn/src/ivoc/htlist.cpp:74 in HTList::Remove()
94: SUMMARY: ThreadSanitizer: data race /home/savulesc/Workspace/nrn/src/ivoc/htlist.cpp:72 in HTList::Remove()
94: SUMMARY: ThreadSanitizer: data race /home/savulesc/Workspace/nrn/src/ivoc/htlist.cpp:74 in HTList::Remove()
94: SUMMARY: ThreadSanitizer: data race /home/savulesc/Workspace/nrn/src/ivoc/htlist.cpp:74 in HTList::Remove()
(venv) savulesc@bbd-cjngk03:~/Workspace/nrn/bldnrntest$ 
```

**Comment by alexsavulescu** [comment]
`Cvode::at_time` sanitizer output:
```cpp
94: ==================
94: WARNING: ThreadSanitizer: data race (pid=2572)
94:   Read of size 8 at 0x7b3c00000bf0 by thread T1:
94:     #0 Cvode::at_time(double, NrnThread*) /home/savulesc/Workspace/nrn/src/nrncvode/cvodeobj.cpp:751 (libnrniv.so+0x38673e)
94:     #1 at_time /home/savulesc/Workspace/nrn/src/nrncvode/cvodestb.cpp:133 (libnrniv.so+0x389e27)
94:     #2 _nrn_current__IClamp /home/savulesc/Workspace/nrn/src/nrnoc/stim.c:266 (libnrniv.so+0x5b8f02)
94:     #3 _nrn_cur__IClamp /home/savulesc/Workspace/nrn/src/nrnoc/stim.c:306 (libnrniv.so+0x5b9236)
94:     #4 Cvode::rhs_memb(CvMembList*, NrnThread*) /home/savulesc/Workspace/nrn/src/nrncvode/cvtrset.cpp:68 (libnrniv.so+0x38a0eb)
94:     #5 Cvode::rhs(NrnThread*) /home/savulesc/Workspace/nrn/src/nrncvode/cvtrset.cpp:35 (libnrniv.so+0x38a2f6)
94:     #6 Cvode::fun_thread_transfer_part2(double*, NrnThread*) /home/savulesc/Workspace/nrn/src/nrncvode/occvode.cpp:671 (libnrniv.so+0x3bbbf1)
94:     #7 Cvode::fun_thread(double, double*, double*, NrnThread*) /home/savulesc/Workspace/nrn/src/nrncvode/occvode.cpp:639 (libnrniv.so+0x3bd049)
94:     #8 f_thread /home/savulesc/Workspace/nrn/src/nrncvode/cvodeobj.cpp:1532 (libnrniv.so+0x384f45)
94:     #9 slave_main /home/savulesc/Workspace/nrn/src/nrnoc/multicore.cpp:337 (libnrniv.so+0x5157ee)
94: 
94:   Previous write of size 8 at 0x7b3c00000bf0 by main thread:
94:     #0 Cvode::at_time(double, NrnThread*) /home/savulesc/Workspace/nrn/src/nrncvode/cvodeobj.cpp:753 (libnrniv.so+0x386759)
94:     #1 at_time /home/savulesc/Workspace/nrn/src/nrncvode/cvodestb.cpp:133 (libnrniv.so+0x389e27)
94:     #2 _nrn_current__IClamp /home/savulesc/Workspace/nrn/src/nrnoc/stim.c:266 (libnrniv.so+0x5b8f02)
94:     #3 _nrn_cur__IClamp /home/savulesc/Workspace/nrn/src/nrnoc/stim.c:306 (libnrniv.so+0x5b9236)
94:     #4 Cvode::rhs_memb(CvMembList*, NrnThread*) /home/savulesc/Workspace/nrn/src/nrncvode/cvtrset.cpp:68 (libnrniv.so+0x38a0eb)
94:     #5 Cvode::rhs(NrnThread*) /home/savulesc/Workspace/nrn/src/nrncvode/cvtrset.cpp:35 (libnrniv.so+0x38a2f6)
94:     #6 Cvode::fun_thread_transfer_part2(double*, NrnThread*) /home/savulesc/Workspace/nrn/src/nrncvode/occvode.cpp:671 (libnrniv.so+0x3bbbf1)
94:     #7 Cvode::fun_thread(double, double*, double*, NrnThread*) /home/savulesc/Workspace/nrn/src/nrncvode/occvode.cpp:639 (libnrniv.so+0x3bd049)
94:     #8 f_thread /home/savulesc/Workspace/nrn/src/nrncvode/cvodeobj.cpp:1532 (libnrniv.so+0x384f45)
94:     #9 nrn_multithread_job(void* (*)(NrnThread*)) /home/savulesc/Workspace/nrn/src/nrnoc/multicore.cpp:1091 (libnrniv.so+0x516d85)
94:     #10 f_gvardt /home/savulesc/Workspace/nrn/src/nrncvode/cvodeobj.cpp:1516 (libnrniv.so+0x384d73)
94:     #11 Cvode::cvode_init(double) /home/savulesc/Workspace/nrn/src/nrncvode/cvodeobj.cpp:1079 (libnrniv.so+0x3891d6)
94:     #12 Cvode::init(double) /home/savulesc/Workspace/nrn/src/nrncvode/cvodeobj.cpp:1177 (libnrniv.so+0x389518)
94:     #13 NetCvode::re_init(double) /home/savulesc/Workspace/nrn/src/nrncvode/netcvode.cpp:3995 (libnrniv.so+0x3a9cfd)
94:     #14 cvode_finitialize(double) /home/savulesc/Workspace/nrn/src/nrncvode/cvodestb.cpp:125 (libnrniv.so+0x389dab)
94:     #15 nrn_finitialize(int, double) /home/savulesc/Workspace/nrn/src/nrnoc/fadvance.cpp:962 (libnrniv.so+0x4fcb2d)
94:     #16 finitialize() /home/savulesc/Workspace/nrn/src/nrnoc/fadvance.cpp:1004 (libnrniv.so+0x4fcbee)
94:     #17 hoc_call() /home/savulesc/Workspace/nrn/src/oc/code.cpp:1389 (libnrniv.so+0x52cc31)
94:     #18 hoc_execute(Inst*) /home/savulesc/Workspace/nrn/src/oc/code.cpp:2682 (libnrniv.so+0x52af71)
94:     #19 hoc_call() /home/savulesc/Workspace/nrn/src/oc/code.cpp:1416 (libnrniv.so+0x52ce68)
94:     #20 hoc_execute(Inst*) /home/savulesc/Workspace/nrn/src/oc/code.cpp:2682 (libnrniv.so+0x52af71)
94:     #21 hoc_call() /home/savulesc/Workspace/nrn/src/oc/code.cpp:1416 (libnrniv.so+0x52ce68)
94:     #22 hoc_execute(Inst*) /home/savulesc/Workspace/nrn/src/oc/code.cpp:2682 (libnrniv.so+0x52af71)
94:     #23 hoc_call() /home/savulesc/Workspace/nrn/src/oc/code.cpp:1416 (libnrniv.so+0x52ce68)
94:     #24 hoc_execute(Inst*) /home/savulesc/Workspace/nrn/src/oc/code.cpp:2682 (libnrniv.so+0x52af71)
94:     #25 hoc_run1 /home/savulesc/Workspace/nrn/src/oc/hoc.cpp:1410 (libnrniv.so+0x539966)
94:     #26 hoc_main1(int, char const**, char const**) /home/savulesc/Workspace/nrn/src/oc/hoc.cpp:1054 (libnrniv.so+0x539b14)
94:     #27 Oc::run(int, char const**) /home/savulesc/Workspace/nrn/src/ivoc/ivoc.cpp:325 (libnrniv.so+0x2ff9b7)
94:     #28 ivocmain_session(int, char const**, char const**, int) /home/savulesc/Workspace/nrn/src/ivoc/ivocmain.cpp:839 (libnrniv.so+0x30796a)
94:     #29 ivocmain(int, char const**, char const**) /home/savulesc/Workspace/nrn/src/ivoc/ivocmain.cpp:415 (libnrniv.so+0x307f0e)
94:     #30 main /home/savulesc/Workspace/nrn/src/ivoc/nrnmain.cpp:53 (nrniv+0x1308)
94: 
94:   Location is heap block of size 240 at 0x7b3c00000b40 allocated by main thread:
94:     #0 operator new(unsigned long) ../../../../src/libsanitizer/tsan/tsan_new_delete.cpp:64 (libtsan.so.0+0x8c032)
94:     #1 NetCvode::alloc_list() /home/savulesc/Workspace/nrn/src/nrncvode/netcvode.cpp:1554 (libnrniv.so+0x391d3a)
94:     #2 NetCvode::init_global() /home/savulesc/Workspace/nrn/src/nrncvode/netcvode.cpp:1607 (libnrniv.so+0x392488)
94:     #3 NetCvode::solver_prepare() /home/savulesc/Workspace/nrn/src/nrncvode/netcvode.cpp:3951 (libnrniv.so+0x3a5044)
94:     #4 nrn_solver_prepare() /home/savulesc/Workspace/nrn/src/nrncvode/cvodestb.cpp:95 (libnrniv.so+0x389bdf)
94:     #5 verify_structure() /home/savulesc/Workspace/nrn/src/nrnoc/fadvance.cpp:832 (libnrniv.so+0x4fbe8c)
94:     #6 nrn_finitialize(int, double) /home/savulesc/Workspace/nrn/src/nrnoc/fadvance.cpp:844 (libnrniv.so+0x4fc301)
94:     #7 finitialize() /home/savulesc/Workspace/nrn/src/nrnoc/fadvance.cpp:1004 (libnrniv.so+0x4fcbee)
94:     #8 hoc_call() /home/savulesc/Workspace/nrn/src/oc/code.cpp:1389 (libnrniv.so+0x52cc31)
94:     #9 hoc_execute(Inst*) /home/savulesc/Workspace/nrn/src/oc/code.cpp:2682 (libnrniv.so+0x52af71)
94:     #10 hoc_call() /home/savulesc/Workspace/nrn/src/oc/code.cpp:1416 (libnrniv.so+0x52ce68)
94:     #11 hoc_execute(Inst*) /home/savulesc/Workspace/nrn/src/oc/code.cpp:2682 (libnrniv.so+0x52af71)
94:     #12 hoc_call() /home/savulesc/Workspace/nrn/src/oc/code.cpp:1416 (libnrniv.so+0x52ce68)
94:     #13 hoc_execute(Inst*) /home/savulesc/Workspace/nrn/src/oc/code.cpp:2682 (libnrniv.so+0x52af71)
94:     #14 hoc_call() /home/savulesc/Workspace/nrn/src/oc/code.cpp:1416 (libnrniv.so+0x52ce68)
94:     #15 hoc_execute(Inst*) /home/savulesc/Workspace/nrn/src/oc/code.cpp:2682 (libnrniv.so+0x52af71)
94:     #16 hoc_run1 /home/savulesc/Workspace/nrn/src/oc/hoc.cpp:1410 (libnrniv.so+0x539966)
94:     #17 hoc_main1(int, char const**, char const**) /home/savulesc/Workspace/nrn/src/oc/hoc.cpp:1054 (libnrniv.so+0x539b14)
94:     #18 Oc::run(int, char const**) /home/savulesc/Workspace/nrn/src/ivoc/ivoc.cpp:325 (libnrniv.so+0x2ff9b7)
94:     #19 ivocmain_session(int, char const**, char const**, int) /home/savulesc/Workspace/nrn/src/ivoc/ivocmain.cpp:839 (libnrniv.so+0x30796a)
94:     #20 ivocmain(int, char const**, char const**) /home/savulesc/Workspace/nrn/src/ivoc/ivocmain.cpp:415 (libnrniv.so+0x307f0e)
94:     #21 main /home/savulesc/Workspace/nrn/src/ivoc/nrnmain.cpp:53 (nrniv+0x1308)
94: 
94:   Thread T1 (tid=2607, running) created by main thread at:
94:     #0 pthread_create ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:962 (libtsan.so.0+0x5ea79)
94:     #1 threads_create_pthread /home/savulesc/Workspace/nrn/src/nrnoc/multicore.cpp:373 (libnrniv.so+0x5154eb)
94:     #2 nrn_threads_create(int, int) /home/savulesc/Workspace/nrn/src/nrnoc/multicore.cpp:554 (libnrniv.so+0x518541)
94:     #3 nthrd /home/savulesc/Workspace/nrn/src/nrniv/../parallel/ocbbs.cpp:897 (libnrniv.so+0x4a9283)
94:     #4 hoc_call_ob_proc /home/savulesc/Workspace/nrn/src/oc/hoc_oop.cpp:759 (libnrniv.so+0x53d042)
94:     #5 hoc_object_component() /home/savulesc/Workspace/nrn/src/oc/hoc_oop.cpp:1174 (libnrniv.so+0x53e570)
94:     #6 hoc_execute(Inst*) /home/savulesc/Workspace/nrn/src/oc/code.cpp:2682 (libnrniv.so+0x52af71)
94:     #7 hoc_ParseExec /home/savulesc/Workspace/nrn/src/oc/code.cpp:566 (libnrniv.so+0x52b199)
94:     #8 hoc_oc /home/savulesc/Workspace/nrn/src/oc/hoc.cpp:1517 (libnrniv.so+0x537cae)
94:     #9 hoc_obj_run /home/savulesc/Workspace/nrn/src/oc/hoc_oop.cpp:347 (libnrniv.so+0x53c30e)
94:     #10 OcJumpImpl::execute(char const*, Object*) /home/savulesc/Workspace/nrn/src/nrniv/../ivoc/ocjump.cpp:205 (libnrniv.so+0x4ad6c3)
94:     #11 OcJump::execute(char const*, Object*) /home/savulesc/Workspace/nrn/src/nrniv/../ivoc/ocjump.cpp:153 (libnrniv.so+0x4ad753)
94:     #12 valid_stmt1 /home/savulesc/Workspace/nrn/src/nrniv/../ivoc/ocjump.cpp:30 (libnrniv.so+0x4ad7f2)
94:     #13 hoc_execute1() /home/savulesc/Workspace/nrn/src/nrniv/../ivoc/ocjump.cpp:55 (libnrniv.so+0x4ad90a)
94:     #14 hoc_call() /home/savulesc/Workspace/nrn/src/oc/code.cpp:1389 (libnrniv.so+0x52cc31)
94:     #15 hoc_execute(Inst*) /home/savulesc/Workspace/nrn/src/oc/code.cpp:2682 (libnrniv.so+0x52af71)
94:     #16 hoc_run1 /home/savulesc/Workspace/nrn/src/oc/hoc.cpp:1410 (libnrniv.so+0x539966)
94:     #17 hoc_main1(int, char const**, char const**) /home/savulesc/Workspace/nrn/src/oc/hoc.cpp:1054 (libnrniv.so+0x539b14)
94:     #18 Oc::run(int, char const**) /home/savulesc/Workspace/nrn/src/ivoc/ivoc.cpp:325 (libnrniv.so+0x2ff9b7)
94:     #19 ivocmain_session(int, char const**, char const**, int) /home/savulesc/Workspace/nrn/src/ivoc/ivocmain.cpp:839 (libnrniv.so+0x30796a)
94:     #20 ivocmain(int, char const**, char const**) /home/savulesc/Workspace/nrn/src/ivoc/ivocmain.cpp:415 (libnrniv.so+0x307f0e)
94:     #21 main /home/savulesc/Workspace/nrn/src/ivoc/nrnmain.cpp:53 (nrniv+0x1308)
94: 
94: SUMMARY: ThreadSanitizer: data race /home/savulesc/Workspace/nrn/src/nrncvode/cvodeobj.cpp:751 in Cvode::at_time(double, NrnThread*)
94: ==================
94: nrniv: /home/savulesc/Workspace/nrn/src/nrncvode/cvodeobj.cpp:775: bool Cvode::at_time(double, NrnThread*): Assertion `te > tstop_ || te <= t0_' failed.
```

**Comment by alexsavulescu** [comment]
Cannot see the assert anymore, however we can still see the hanging in the NEURON CI.

**Comment by alexsavulescu** [comment]
> Cannot see the assert anymore, however we can still see the hanging in the NEURON CI.

cannot see the hanging anymore in the NEURON PR.

**Comment by alexsavulescu** [comment]
I am a bit puzzled as to why the updates from this PR are needed, but without them we cannot integrate `nrntest` into the NEURON CMake testing.

**Pull request merged**
